# Number of days of inactivity before an issue becomes stale
daysUntilStale: 14

# Number of days of inactivity before a stale issue is closed
daysUntilClose: 30

# Issues with these labels will never be considered stale
# exemptLabels:
#   - pinned
#   - security

# Only issues or pull requests with all of these labels are check if stale.
onlyLabels:
  - "Status: Abandoned"
  - "Type: Question"

# Label to use when marking as stale
staleLabel: stale

# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had
  activity in the past 2 weeks. It will be closed if no further activity occurs. Thank you
  for your contributions.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: This issue is being closed after 30 days of inactivity. Thank you. 